### PR TITLE
add progress support for multiple config

### PR DESCRIPTION
**Pull request by incebellipipo**

### CODE REVIEW

**Comment by kltm** [comment]
@incebellipipo Not something I have personally and cannot test. I just want to confirm that this works well for you with single and multi-drive configs.

**Comment by incebellipipo** [comment]
I just tested it in multi-drive config. I can test single-drive config as well and send the results.

**Comment by kltm** [comment]
No need to send results--if you've tested in a single-drive environment, I'll take your word for it.

**Comment by incebellipipo** [comment]
Ok, I'll do the test today and let you know

**Comment by incebellipipo** [comment]
Yup,
If none disks rebuilding it shows nothing
If one virtual disk rebuilding it shows that
If two, it shows also two of them.

Tested in esxi 6.7.

Also, esxi server doesn't have bash installed. I don't know why but it has only sh. I changed shebang as script runs with sh. It works, however I haven't checked if bash specific features used in script or not. I may be good to have sh as interpreter.

**Comment by kltm** [comment]
Okay, merging sounds good. Thank you!

**Pull request merged**
